spring:
  application:
    name: auth-service
jwt:
  secret: secretKey
  issuer: Auth-Service
hostname:
  userservice: http://localhost:9098
path:
  getUserByUserName: /v1/users
logging:
  level:
    com:
      userservice: DEBUG
    root: INFO
#Eureka Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}



