jwt:
  secret: secretKey
  issuer: Auth-Service
hostname:
  userservice: http://localhost:9098
path:
  getUserByUserName: /v1/users
logging:
  level:
    com:
      userservice: DEBUG
    root: INFO


